# 基础镜像
FROM nginx:latest

# 挂载目录
VOLUME /home/DPMS/projects/DPMS-ui
# 指定路径
WORKDIR /home/DPMS/projects/DPMS-ui
# 复制conf文件到路径
COPY ./demo-frontend/nginx/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./demo-frontend/dist /home/DPMS/projects/DPMS-ui