spring:
  profiles:
    active: dev
  mail:
    host: smtp.163.com
    username: 18223818435@163.com
    password: RPQIGCSLHXFUFOIL
    port: 465
    properties:
      from: 18223818435@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  security:
    jwt:
      key: abcdefghk
      expire: 7
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss