spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/property_management?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  task:
    scheduling:
      pool:
        size: 1
springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v1/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"
files:
  upload:
    #图片文件存储位置
    path: D:/CodeDevelopment/uploaded/
