spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meeting?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    username: 18223818435@163.com
    password: RPQIGCSLHXFUFOIL
    port: 465
    properties:
      from: 18223818435@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  security:
    jwt:
      key: abcdefghk
      expire: 7
files:
  upload:
    #图片文件存储位置
    path: D:/CodeDevelopment/uploaded/