spring:
  profiles:
    active: dev # 指定环境
  mail:
    host: smtp.XX.com  #  邮箱服务器
    username: XXX@XX.com # 发件人邮箱
    password: XXXXXXXXXX  #  邮箱授权码
    port: 465
    properties:
      from: XXX@XXX.com #  发件人邮箱地址，需对应邮箱开通smtp服务
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  security:
    jwt:
      key: abcdefghk  #  jwt密钥
      expire: 7 #  jwt过期时间，单位：天
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss